#!/bin/sh

if [ ! $# -eq 1 ] ; then
    echo "Usage:";
    echo "$0 file.pmx";
	echo -e "\nDescription:"
	echo "Calls chords_transpose.pl script to transpose chords."
	echo "New temporary file [file]-tex.pmx is created."
	echo "Then calls pmxab to create [file]-tex.tex file."
	echo "Finally temporary file ([file]-tex.pmx) is removed and [file]-tex.tex file is renamed to [file].tex."
    exit -1;
fi

file=$1

fileBase=`basename $file .pmx`
filePmx=$fileBase.pmx
if [ ! -f $filePmx ] ; then
	echo "File $filePmx does not exist."
	exit -1
fi

tempFileBase=${fileBase}-tex
tempFilePmx=$tempFileBase.pmx

# here it is - do chords transposition ...
cat $filePmx | chords_transpose.pl > $tempFilePmx
pmxab $tempFilePmx
if [ ! $? -eq 0 ]
then
    echo "PMX process fail!"
    exit -1
fi

#
# If you want to use csplain/pdfcsplain instead of etex/pdfetex
# It is required to remove line
# \setmaxslurs{24}\setmaxinstruments{24}
# generated by pmx2.7
#
#sed -i -e '/\\setmaxslurs{24}\\setmaxinstruments{24}/d' $tempFileBase.tex

mv $tempFileBase.tex $fileBase.tex
mv $tempFileBase.pml $fileBase.pml
rm $tempFilePmx
